version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app

  db:
    container_name: "database"
    image: mysql:
    command:
    restart: always
    ports:
      - '3308:3306'
    environment:
      - MYSQL_DATABASE:
      - MYSQL_USER :
      - MYSQL_PASSWORD :
      - MYSQL_ROOT_PASSWORD :
