version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - "db"

  db:
    container_name: "database-mysql"
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "blog-estudo"
      MYSQL_USER: "alphard"
      MYSQL_PASSWORD: "teste"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
      - "./db.sql:/docker-entrypoint-initdb.d/1.sql"
