CREATE SCHEMA IF NOT EXISTS `blog-estudo` DEFAULT CHARACTER
SET
  utf8;

USE `blog-estudo`;

CREATE TABLE
  IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
  );
